schema_version = "1.0.0"
id = "amh2b"
version = "2.6.0"
name = "Automate MakeHuman 2 Blender"
tagline = "MakeHuman Automation"
maintainer = "Dave"
type = "add-on"
blender_version_min = "4.2.0"
license = [
  "SPDX:GPL-3.0-or-later",
]

[permissions]
files = "Load and save data"

