{
    "label": "Mixamo 5 Finger to Import MHX",
    "data": [
        { "op": "global_rotate_bone", "data": [
                ("clavicle.L", "y", -15),
                ("clavicle.L", "z", 5),
                ("upper_arm.fk.L", "y", -28.5),
                ("upper_arm.fk.L", "z", -2.5),
                ("forearm.fk.L", "z", 41.5),
                ("forearm.fk.L", "y", -3.5),
                ("hand.fk.L", "y", -5),
                ("hand.fk.L", "x", 5),
                ("thumb.L", "x", -5.25),
                ("thumb.L", "y", 4),
                ("thumb.L", "z", 4),
                ("index.L", "x", 20),
                ("index.L", "y", -6.75),
                ("middle.L", "y", -5),
                ("ring.L", "y", -5.2),
                ("ring.L", "z", -2.5),
                ("pinky.L", "y", -8),
                ("pinky.L", "z", -8),
                ("thigh.fk.L", "y", 7),
                ("foot.fk.L", "y", -6.5),
                ("clavicle.R", "y", 15),
                ("clavicle.R", "z", -5),
                ("upper_arm.fk.R", "y", 28.5),
                ("upper_arm.fk.R", "z", 2.5),
                ("forearm.fk.R", "z", -41.5),
                ("forearm.fk.R", "y", 3.5),
                ("hand.fk.R", "y", 5),
                ("hand.fk.R", "x", 5),
                ("thumb.R", "x", -5.25),
                ("thumb.R", "y", -4),
                ("thumb.R", "z", -4),
                ("index.R", "x", 20),
                ("index.R", "y", 6.75),
                ("middle.R", "y", 5),
                ("ring.R", "y", 5.2),
                ("ring.R", "z", 2.5),
                ("pinky.R", "y", 8),
                ("pinky.R", "z", 8),
                ("thigh.fk.R", "y", -7),
                ("foot.fk.R", "y", 6.5),
                ]
            }
        ]
    }
