{
    "label": "CMU MotionBuilder2 to MPFB2 Game engine",
    "data": [
        { "op": "create_transfer_armature" },
        { "op": "transfer_transforms", "data": [ ("Hips", "pelvis", 0.0, 0.0, 1.0),
            ("Neck1", "neck_01", 0.0, 0.0, 1.0) ] },
        { "op": "transfer_rotation", "data": [ ("LowerBack", "spine_01"),
            ("Spine", "spine_03"), ("Head", "head"), ] },
        { "op": "transfer_transforms", "data": [ ("LeftShoulder", "clavicle_l", 0.0, 0.0, 1.0) ] },
        { "op": "transfer_rotation", "data": [ ("LeftArm", "upperarm_l"),
            ("LeftForeArm", "lowerarm_l"), ("LeftHand", "hand_l"), ("LThumb", "thumb_01_l"),
            ("LeftHandFinger1", "index_01_l"), ("LeftHandFinger1", "middle_01_l"),
            ("LeftHandFinger1", "ring_01_l"), ("LeftHandFinger1", "pinky_01_l"), ] },
        { "op": "transfer_rotation", "data": [ ("LeftUpLeg", "thigh_l"), ("LeftLeg", "calf_l"),
            ("LeftFoot", "foot_l"), ("LeftToeBase", "ball_l"), ] },
        { "op": "transfer_transforms", "data": [ ("RightShoulder", "clavicle_r", 0.0, 0.0, 1.0) ] },
        { "op": "transfer_rotation", "data": [ ("RightArm", "upperarm_r"),
            ("RightForeArm", "lowerarm_r"), ("RightHand", "hand_r"), ("LThumb", "thumb_01_r"),
            ("RightHandFinger1", "index_01_r"), ("RightHandFinger1", "middle_01_r"),
            ("RightHandFinger1", "ring_01_r"), ("RightHandFinger1", "pinky_01_r"), ] },
        { "op": "transfer_rotation", "data": [ ("RightUpLeg", "thigh_r"), ("RightLeg", "calf_r"),
            ("RightFoot", "foot_r"), ("RightToeBase", "ball_r"), ] },
        ],
    }
