{
    "label": "Mixamo 65 Bone to MPFB2 Game engine",
    "data": [
        { "op": "create_transfer_armature" },
        { "op": "transfer_transforms", "data": [ ("*:Hips", "pelvis", 0.0, 0.0, 1.0), ] },
        { "op": "transfer_rotation", "data": [ ("*:Spine", "spine_02"), ("*:Spine1", "spine_03"),
            ("*:Neck", "neck_01"), ("*:Head", "head"), ] },
        { "op": "transfer_transforms", "data": [ ("*:LeftShoulder", "clavicle_l", 0.0, 0.0, 1.0), ] },
        { "op": "transfer_rotation", "data": [ ("*:LeftArm", "upperarm_l"),
            ("*:LeftForeArm", "lowerarm_l"), ("*:LeftHand", "hand_l"), ("*:LeftHandThumb1", "thumb_01_l"),
            ("*:LeftHandThumb2", "thumb_02_l"), ("*:LeftHandThumb3", "thumb_03_l"),
            ("*:LeftHandIndex1", "index_01_l"), ("*:LeftHandIndex2", "index_02_l"),
            ("*:LeftHandIndex3", "index_03_l"), ("*:LeftHandMiddle1", "middle_01_l"),
            ("*:LeftHandMiddle2", "middle_02_l"), ("*:LeftHandMiddle3", "middle_03_l"),
            ("*:LeftHandRing1", "ring_01_l"), ("*:LeftHandRing2", "ring_02_l"),
            ("*:LeftHandRing3", "ring_03_l"), ("*:LeftHandPinky1", "pinky_01_l"),
            ("*:LeftHandPinky2", "pinky_02_l"), ("*:LeftHandPinky3", "pinky_03_l"), ] },
        { "op": "transfer_rotation", "data": [ ("*:LeftUpLeg", "thigh_l"), ("*:LeftLeg", "calf_l"),
            ("*:LeftFoot", "foot_l"), ("*:LeftToeBase", "ball_l"), ] },
        { "op": "transfer_transforms", "data": [ ("*:RightShoulder", "clavicle_r", 0.0, 0.0, 1.0), ] },
        { "op": "transfer_rotation", "data": [ ("*:RightArm", "upperarm_r"),
            ("*:RightForeArm", "lowerarm_r"), ("*:RightHand", "hand_r"), ("*:RightHandThumb1", "thumb_01_r"),
            ("*:RightHandThumb2", "thumb_02_r"), ("*:RightHandThumb3", "thumb_03_r"),
            ("*:RightHandIndex1", "index_01_r"), ("*:RightHandIndex2", "index_02_r"),
            ("*:RightHandIndex3", "index_03_r"), ("*:RightHandMiddle1", "middle_01_r"),
            ("*:RightHandMiddle2", "middle_02_r"), ("*:RightHandMiddle3", "middle_03_r"),
            ("*:RightHandRing1", "ring_01_r"), ("*:RightHandRing2", "ring_02_r"),
            ("*:RightHandRing3", "ring_03_r"), ("*:RightHandPinky1", "pinky_01_r"),
            ("*:RightHandPinky2", "pinky_02_r"), ("*:RightHandPinky3", "pinky_03_r"), ] },
        { "op": "transfer_rotation", "data": [ ("*:RightUpLeg", "thigh_r"), ("*:RightLeg", "calf_r"),
            ("*:RightFoot", "foot_r"), ("*:RightToeBase", "ball_r"), ] },

        ],
    }
