{
    "label": "Mixamo 65 Bone to MPFB2 Default FK",
    "data": [
        { "op": "create_transfer_armature" },
        { "op": "transfer_transforms", "data": [ ("*:Hips", "root", 0.0, 0.0, 1.0) ] },
        { "op": "transfer_rotation", "data": [ ("*:Spine", "spine03"), ("*:Spine1", "spine02"),
            ("*:Spine2", "spine01"), ("*:Neck", "neck01"), ("*:Head", "head") ] },
        { "op": "transfer_rotation", "data": [ ("*:LeftShoulder", "clavicle.L"), ("*:LeftArm", "upperarm01.L"),
            ("*:LeftForeArm", "lowerarm01.L"), ("*:LeftHand", "wrist.L"),
            ("*:LeftHandThumb1", "finger1-1.L"), ("*:LeftHandThumb2", "finger1-2.L"),
            ("*:LeftHandThumb3", "finger1-3.L"),
            ("*:LeftHandIndex1", "finger2-1.L"), ("*:LeftHandIndex2", "finger2-2.L"),
            ("*:LeftHandIndex3", "finger2-3.L"),
            ("*:LeftHandMiddle1", "finger3-1.L"), ("*:LeftHandMiddle2", "finger3-2.L"),
            ("*:LeftHandMiddle3", "finger3-3.L"),
            ("*:LeftHandRing1", "finger4-1.L"), ("*:LeftHandRing2", "finger4-2.L"),
            ("*:LeftHandRing3", "finger4-3.L"),
            ("*:LeftHandPinky1", "finger5-1.L"), ("*:LeftHandPinky2", "finger5-2.L"),
            ("*:LeftHandPinky3", "finger5-3.L"), ] },
        { "op": "transfer_rotation", "data": [ ("*:LeftUpLeg", "upperleg01.L"), ("*:LeftLeg", "lowerleg01.L"),
            ("*:LeftFoot", "foot.L"), ("*:LeftToeBase", "toe1-1.L"), ("*:LeftToeBase", "toe2-1.L"),
            ("*:LeftToeBase", "toe3-1.L"), ("*:LeftToeBase", "toe4-1.L"), ("*:LeftToeBase", "toe5-1.L"), ] },
        { "op": "transfer_rotation", "data": [ ("*:RightShoulder", "clavicle.R"), ("*:RightArm", "upperarm01.R"),
            ("*:RightForeArm", "lowerarm01.R"), ("*:RightHand", "wrist.R"),
            ("*:RightHandThumb1", "finger1-1.R"), ("*:RightHandThumb2", "finger1-2.R"),
            ("*:RightHandThumb3", "finger1-3.R"),
            ("*:RightHandIndex1", "finger2-1.R"), ("*:RightHandIndex2", "finger2-2.R"),
            ("*:RightHandIndex3", "finger2-3.R"),
            ("*:RightHandMiddle1", "finger3-1.R"), ("*:RightHandMiddle2", "finger3-2.R"),
            ("*:RightHandMiddle3", "finger3-3.R"),
            ("*:RightHandRing1", "finger4-1.R"), ("*:RightHandRing2", "finger4-2.R"),
            ("*:RightHandRing3", "finger4-3.R"),
            ("*:RightHandPinky1", "finger5-1.R"), ("*:RightHandPinky2", "finger5-2.R"),
            ("*:RightHandPinky3", "finger5-3.R"), ] },
        { "op": "transfer_rotation", "data": [ ("*:RightUpLeg", "upperleg01.R"), ("*:RightLeg", "lowerleg01.R"),
            ("*:RightFoot", "foot.R"), ("*:RightToeBase", "toe1-1.R"), ("*:RightToeBase", "toe2-1.R"),
            ("*:RightToeBase", "toe3-1.R"), ("*:RightToeBase", "toe4-1.R"), ("*:RightToeBase", "toe5-1.R"), ] },
        ]
    }
