{
    "label": "Mixamo 65 Bone to Rigify",
    "data": [
        { "op": "create_transfer_armature" },
        { "op": "transfer_transforms", "data": [ ("*:Hips", "torso", 0.0, 0.0, 1.0) ] },
        { "op": "transfer_rotation", "data": [ ("*:Spine", "spine_fk.002"), ("*:Spine1", "spine_fk.003"),
            ("*:Spine2", "spine_fk.004"), ("*:Neck", "neck"), ("*:Head", "neck02"), ("*:Head", "head"),
            ] },
        { "op": "transfer_transforms", "data": [ ("*:LeftForeArm", "forearm_tweak.L", 0.0, 0.0, 1.0),
            ("*:LeftHand", "hand_ik.L", 0.0, 0.0, 1.0), ("*:LeftUpLeg", "thigh_ik.L", 0.0, 0.0, 1.0),
            ("*:LeftLeg", "shin_tweak.L", 0.0, 0.0, 1.0), ("*:LeftFoot", "foot_ik.L", 0.0, 0.0, 1.0),
            ] },
        { "op": "transfer_rotation", "data": [ ("*:LeftShoulder", "shoulder.L"), ("*:LeftArm", "upper_arm_ik.L"),
            ("*:LeftHandThumb1", "thumb.01.L"), ("*:LeftHandThumb2", "thumb.02.L"),
            ("*:LeftHandThumb3", "thumb.03.L"),
            ("*:LeftHandIndex1", "f_index.01.L"), ("*:LeftHandIndex2", "f_index.02.L"),
            ("*:LeftHandIndex3", "f_index.03.L"),
            ("*:LeftHandMiddle1", "f_middle.01.L"), ("*:LeftHandMiddle2", "f_middle.02.L"),
            ("*:LeftHandMiddle3", "f_middle.03.L"),
            ("*:LeftHandRing1", "f_ring.01.L"), ("*:LeftHandRing2", "f_ring.02.L"),
            ("*:LeftHandRing3", "f_ring.03.L"),
            ("*:LeftHandPinky1", "f_pinky.01.L"), ("*:LeftHandPinky2", "f_pinky.02.L"),
            ("*:LeftHandPinky3", "f_pinky.03.L"),
            ("*:LeftToeBase", "toe1-1_master.L"), ("*:LeftToeBase", "toe2-1_master.L"),
            ("*:LeftToeBase", "toe3-1_master.L"), ("*:LeftToeBase", "toe4-1_master.L"),
            ("*:LeftToeBase", "toe5-1_master.L"),
            ] },
        { "op": "transfer_transforms", "data": [ ("*:RightForeArm", "forearm_tweak.R", 0.0, 0.0, 1.0),
            ("*:RightHand", "hand_ik.R", 0.0, 0.0, 1.0), ("*:RightUpLeg", "thigh_ik.R", 0.0, 0.0, 1.0),
            ("*:RightLeg", "shin_tweak.R", 0.0, 0.0, 1.0), ("*:RightFoot", "foot_ik.R", 0.0, 0.0, 1.0),
            ] },
        { "op": "transfer_rotation", "data": [ ("*:RightShoulder", "shoulder.R"), ("*:RightArm", "upper_arm_ik.R"),
            ("*:RightHandThumb1", "thumb.01.R"), ("*:RightHandThumb2", "thumb.02.R"),
            ("*:RightHandThumb3", "thumb.03.R"),
            ("*:RightHandIndex1", "f_index.01.R"), ("*:RightHandIndex2", "f_index.02.R"),
            ("*:RightHandIndex3", "f_index.03.R"),
            ("*:RightHandMiddle1", "f_middle.01.R"), ("*:RightHandMiddle2", "f_middle.02.R"),
            ("*:RightHandMiddle3", "f_middle.03.R"),
            ("*:RightHandRing1", "f_ring.01.R"), ("*:RightHandRing2", "f_ring.02.R"),
            ("*:RightHandRing3", "f_ring.03.R"),
            ("*:RightHandPinky1", "f_pinky.01.R"), ("*:RightHandPinky2", "f_pinky.02.R"),
            ("*:RightHandPinky3", "f_pinky.03.R"),
            ("*:RightToeBase", "toe1-1_master.R"), ("*:RightToeBase", "toe2-1_master.R"),
            ("*:RightToeBase", "toe3-1_master.R"), ("*:RightToeBase", "toe4-1_master.R"),
            ("*:RightToeBase", "toe5-1_master.R"),
            ] },
        ]
    }
