{
    "label": "Mixamo 65 Bone to MPFB2 Default IK",
    "description": "Requires MPFB2 Default IK with Finger Helpers set to include 'Individual grip' or 'IK point'",
    "data": [
        { "op": "create_transfer_armature" },
        { "op": "transfer_transforms", "data": [ ("*:Hips", "root", 0.0, 0.0, 1.0),
            ("*:Hips", "left_hip_ik", 0.0, 0.0, 1.0), ("*:Hips", "right_hip_ik", 0.0, 0.0, 1.0) ] },
        { "op": "transfer_rotation", "data": [ ("*:Spine", "spine03"), ("*:Spine1", "spine02"),
            ("*:Spine2", "spine01"), ("*:Neck", "neck01"), ("*:Head", "neck02"), ("*:Head", "head") ] },
        { "op": "transfer_transforms", "data": [ ("*:LeftForeArm", "left_elbow_ik", 0.0, 0.0, 1.0),
            ("*:LeftHand", "left_hand_ik", 0.0, 0.0, 1.0), ("*:LeftLeg", "left_knee_ik", 0.0, 0.0, 1.0),
            ("*:LeftFoot", "left_foot_ik", 0.0, 0.0, 1.0) ] },
        { "op": "transfer_rotation", "data": [ ("*:LeftShoulder", "clavicle.L"),
            ("*:LeftHandThumb3", "left_finger1_grip"), ("*:LeftHandIndex3", "left_finger2_grip"),
            ("*:LeftHandMiddle3", "left_finger3_grip"), ("*:LeftHandRing3", "left_finger4_grip"),
            ("*:LeftHandPinky3", "left_finger5_grip"), ("*:LeftToeBase", "toe1-1.L"), ("*:LeftToeBase", "toe2-1.L"),
            ("*:LeftToeBase", "toe3-1.L"), ("*:LeftToeBase", "toe4-1.L"), ("*:LeftToeBase", "toe5-1.L") ] },
        { "op": "transfer_transforms", "data": [ ("*:RightForeArm", "right_elbow_ik", 0.0, 0.0, 1.0),
            ("*:RightHand", "right_hand_ik", 0.0, 0.0, 1.0), ("*:RightLeg", "right_knee_ik", 0.0, 0.0, 1.0),
            ("*:RightFoot", "right_foot_ik", 0.0, 0.0, 1.0) ] },
        { "op": "transfer_rotation", "data": [ ("*:RightShoulder", "clavicle.R"),
            ("*:RightHandThumb3", "right_finger1_grip"), ("*:RightHandIndex3", "right_finger2_grip"),
            ("*:RightHandMiddle3", "right_finger3_grip"), ("*:RightHandRing3", "right_finger4_grip"),
            ("*:RightHandPinky3", "right_finger5_grip"), ("*:RightToeBase", "toe1-1.R"),
            ("*:RightToeBase", "toe2-1.R"), ("*:RightToeBase", "toe3-1.R"), ("*:RightToeBase", "toe4-1.R"),
            ("*:RightToeBase", "toe5-1.R") ] },
        { "op": "transfer_transforms", "data": [ ("*:LeftHandThumb3", "left_finger1_point_ik", 0.0, 0.0, 1.0),
            ("*:LeftHandIndex3", "left_finger2_point_ik", 0.0, 0.0, 1.0),
            ("*:LeftHandMiddle3", "left_finger3_point_ik", 0.0, 0.0, 1.0),
            ("*:LeftHandRing3", "left_finger4_point_ik", 0.0, 0.0, 1.0),
            ("*:LeftHandPinky3", "left_finger5_point_ik", 0.0, 0.0, 1.0), ] },
        { "op": "transfer_transforms", "data": [ ("*:RightHandThumb3", "right_finger1_point_ik", 0.0, 0.0, 1.0),
            ("*:RightHandIndex3", "right_finger2_point_ik", 0.0, 0.0, 1.0),
            ("*:RightHandMiddle3", "right_finger3_point_ik", 0.0, 0.0, 1.0),
            ("*:RightHandRing3", "right_finger4_point_ik", 0.0, 0.0, 1.0),
            ("*:RightHandPinky3", "right_finger5_point_ik", 0.0, 0.0, 1.0), ] },
        ]
    }
